import type { Tiptype } from "../types/tips";

export const testTips:Tiptype[] = [
  {
    "id": "1",
    "livescoreId": "ls_001",
    "date": "2024-12-25",
    "league": "Premier League",
    "homeTeam": "Manchester City",
    "awayTeam": "Liverpool",
    "prediction": "Over 2.5",
    "reason": "Both teams have scored in their last 5 matches with an average of 3.2 goals per game.",
    "time": "15:00",
    "score": "2-1",
    "matchStatus": "Live",
    "type": "premium",
    "status": "pending",
    "markets": "Over 2.5 Goals"
  },
  {
    "id": "2",
    "livescoreId": "ls_002",
    "date": "2024-12-25",
    "league": "La Liga",
    "homeTeam": "Real Madrid",
    "awayTeam": "Barcelona",
    "prediction": "GG",
    "reason": "El Clasico matches historically feature goals from both sides, with both teams in excellent attacking form.",
    "time": "20:00",
    "score": "0-0",
    "matchStatus": "Not Started",
    "type": "premium",
    "status": "pending",
    "markets": "GG"
  },
  {
    "id": "3",
    "livescoreId": "ls_003",
    "date": "2024-12-24",
    "league": "Serie A",
    "homeTeam": "Juventus",
    "awayTeam": "AC Milan",
    "prediction": "1",
    "reason": "Juventus has won 4 of their last 5 home games and Milan is missing key defenders.",
    "time": "18:45",
    "score": "3-1",
    "matchStatus": "Finished",
    "type": "basic",
    "status": "won",
    "markets": "1X2"
  },
  {
    "id": "4",
    "livescoreId": "ls_004",
    "date": "2024-12-25",
    "league": "Bundesliga",
    "homeTeam": "Bayern Munich",
    "awayTeam": "Borussia Dortmund",
    "prediction": "Over 2.5",
    "reason": "Der Klassiker averages 3.8 goals per match with both teams playing offensive football.",
    "time": "17:30",
    "score": "1-0",
    "matchStatus": "Live",
    "type": "premium",
    "status": "pending",
    "markets": "Over 2.5 Goals"
  },
  {
    "id": "5",
    "livescoreId": "ls_005",
    "date": "2024-12-24",
    "league": "Ligue 1",
    "homeTeam": "PSG",
    "awayTeam": "Marseille",
    "prediction": "1",
    "reason": "PSG dominates at home with a 90% win rate this season against top 5 opponents.",
    "time": "21:00",
    "score": "2-0",
    "matchStatus": "Finished",
    "type": "premium",
    "status": "won",
    "markets": "1X2"
  },
  {
    "id": "6",
    "livescoreId": "ls_006",
    "date": "2024-12-25",
    "league": "Championship",
    "homeTeam": "Leeds United",
    "awayTeam": "Sheffield United",
    "prediction": "BTTS",
    "reason": "Both teams have conceded and scored in 7 of their last 8 matches.",
    "time": "12:30",
    "score": "1-1",
    "matchStatus": "Live",
    "type": "basic",
    "status": "pending",
    "markets": "BTTS"
  },
  {
    "id": "7",
    "livescoreId": "ls_007",
    "date": "2024-12-24",
    "league": "Premier League",
    "homeTeam": "Arsenal",
    "awayTeam": "Chelsea",
    "prediction": "GG",
    "reason": "Both teams have potent attacks and have been involved in high-scoring London derbies.",
    "time": "16:30",
    "score": "2-2",
    "matchStatus": "Finished",
    "type": "premium",
    "status": "won",
    "markets": "GG"
  },
  {
    "id": "8",
    "livescoreId": "ls_008",
    "date": "2024-12-25",
    "league": "Serie A",
    "homeTeam": "Inter Milan",
    "awayTeam": "Napoli",
    "prediction": "Handicap -1",
    "reason": "Inter has a strong home record and Napoli is struggling on the road with 3 consecutive away losses.",
    "time": "19:45",
    "score": "0-0",
    "matchStatus": "Not Started",
    "type": "premium",
    "status": "pending",
    "markets": "Handicap"
  },
  {
    "id": "9",
    "livescoreId": "ls_009",
    "date": "2024-12-24",
    "league": "Bundesliga",
    "homeTeam": "RB Leipzig",
    "awayTeam": "Bayer Leverkusen",
    "prediction": "Over 2.5",
    "reason": "Both teams play attacking football with an average of 3.5 goals in their head-to-head matches.",
    "time": "14:30",
    "score": "2-2",
    "matchStatus": "Finished",
    "type": "basic",
    "status": "lost",
    "markets": "Over 2.5 Goals"
  },
  {
    "id": "10",
    "livescoreId": "ls_010",
    "date": "2024-12-25",
    "league": "La Liga",
    "homeTeam": "Atletico Madrid",
    "awayTeam": "Sevilla",
    "prediction": "X",
    "reason": "Recent form suggests a tight match with 3 of their last 4 meetings ending in draws.",
    "time": "18:00",
    "score": "0-0",
    "matchStatus": "Not Started",
    "type": "basic",
    "status": "pending",
    "markets": "1X2"
  },
  {
    "id": "11",
    "livescoreId": "ls_011",
    "date": "2024-12-24",
    "league": "Premier League",
    "homeTeam": "Tottenham",
    "awayTeam": "Newcastle",
    "prediction": "BTTS",
    "reason": "Both teams have scored in 6 of their last 7 matches with leaky defenses on both sides.",
    "time": "13:00",
    "score": "3-2",
    "matchStatus": "Finished",
    "type": "basic",
    "status": "won",
    "markets": "BTTS"
  },
  {
    "id": "12",
    "livescoreId": "ls_012",
    "date": "2024-12-25",
    "league": "Ligue 1",
    "homeTeam": "Monaco",
    "awayTeam": "Lyon",
    "prediction": "GG",
    "reason": "Monaco's attack is firing on all cylinders and Lyon always scores away from home.",
    "time": "16:00",
    "score": "1-0",
    "matchStatus": "Live",
    "type": "premium",
    "status": "pending",
    "markets": "GG"
  },
  {
    "id": "13",
    "livescoreId": "ls_013",
    "date": "2024-12-24",
    "league": "Serie A",
    "homeTeam": "Roma",
    "awayTeam": "Lazio",
    "prediction": "Over 2.5",
    "reason": "Derby della Capitale is always fiery with both teams desperate for bragging rights.",
    "time": "20:45",
    "score": "1-3",
    "matchStatus": "Finished",
    "type": "premium",
    "status": "won",
    "markets": "Over 2.5 Goals"
  },
  {
    "id": "14",
    "livescoreId": "ls_014",
    "date": "2024-12-25",
    "league": "Bundesliga",
    "homeTeam": "Wolfsburg",
    "awayTeam": "Frankfurt",
    "prediction": "2",
    "reason": "Frankfurt has superior away form with 4 wins in their last 5 road matches.",
    "time": "15:30",
    "score": "0-0",
    "matchStatus": "Not Started",
    "type": "basic",
    "status": "pending",
    "markets": "1X2"
  },
  {
    "id": "15",
    "livescoreId": "ls_015",
    "date": "2024-12-24",
    "league": "La Liga",
    "homeTeam": "Valencia",
    "awayTeam": "Real Sociedad",
    "prediction": "BTTS",
    "reason": "Valencia's defense is shaky but they score at home, while Sociedad never fails to find the net.",
    "time": "19:00",
    "score": "0-1",
    "matchStatus": "Finished",
    "type": "basic",
    "status": "lost",
    "markets": "BTTS"
  },
  {
    "id": "16",
    "livescoreId": "ls_016",
    "date": "2024-12-25",
    "league": "Premier League",
    "homeTeam": "Aston Villa",
    "awayTeam": "Manchester United",
    "prediction": "Handicap +1",
    "reason": "Villa is resilient at home and United's away form has been inconsistent this season.",
    "time": "14:00",
    "score": "2-1",
    "matchStatus": "Live",
    "type": "premium",
    "status": "pending",
    "markets": "Handicap"
  },
  {
    "id": "17",
    "livescoreId": "ls_017",
    "date": "2024-12-24",
    "league": "Championship",
    "homeTeam": "Southampton",
    "awayTeam": "West Brom",
    "prediction": "1",
    "reason": "Southampton is unbeaten in 6 home games with a solid defensive record.",
    "time": "15:00",
    "score": "2-1",
    "matchStatus": "Finished",
    "type": "basic",
    "status": "won",
    "markets": "1X2"
  },
  {
    "id": "18",
    "livescoreId": "ls_018",
    "date": "2024-12-25",
    "league": "Ligue 1",
    "homeTeam": "Lille",
    "awayTeam": "Nice",
    "prediction": "Over 2.5",
    "reason": "Lille's home matches average 3.1 goals and Nice plays open football on the road.",
    "time": "21:00",
    "score": "0-0",
    "matchStatus": "Not Started",
    "type": "premium",
    "status": "pending",
    "markets": "Over 2.5 Goals"
  },
  {
    "id": "19",
    "livescoreId": "ls_019",
    "date": "2024-12-24",
    "league": "Serie A",
    "homeTeam": "Atalanta",
    "awayTeam": "Fiorentina",
    "prediction": "GG",
    "reason": "Atalanta's attacking style guarantees goals and Fiorentina has scored in every away match.",
    "time": "17:30",
    "score": "3-2",
    "matchStatus": "Finished",
    "type": "basic",
    "status": "won",
    "markets": "GG"
  },
  {
    "id": "20",
    "livescoreId": "ls_020",
    "date": "2024-12-25",
    "league": "Bundesliga",
    "homeTeam": "Stuttgart",
    "awayTeam": "Monchengladbach",
    "prediction": "BTTS",
    "reason": "Both teams have defensive issues but possess quality attackers capable of scoring.",
    "time": "17:30",
    "score": "1-1",
    "matchStatus": "Live",
    "type": "basic",
    "status": "pending",
    "markets": "BTTS"
  }
]